import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Minimal .env loader (no dependency): KEY=VALUE lines, existing env wins.
function loadDotEnv() {
	if (!fs.existsSync(".env")) return;
	for (const line of fs.readFileSync(".env", "utf8").split("\n")) {
		const m = line.match(/^\s*([\w.]+)\s*=\s*(.*?)\s*$/);
		if (!m) continue;
		const key = m[1];
		const val = m[2].replace(/^["']|["']$/g, "");
		if (!(key in process.env)) process.env[key] = val;
	}
}
loadDotEnv();

const prod = process.argv[2] === "production";

// Where to emit. If OBSIDIAN_PLUGIN_DIR is set (see .env), build straight into
// the vault plugin folder; otherwise emit main.js into the repo (CI / clean build).
const outDir = process.env.OBSIDIAN_PLUGIN_DIR || ".";
const outfile = outDir === "." ? "main.js" : path.join(outDir, "main.js");

// After each successful build, sync the static files Obsidian needs next to main.js.
const syncStatics = {
	name: "sync-statics",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0 || outDir === ".") return;
			fs.mkdirSync(outDir, { recursive: true });
			for (const f of ["manifest.json", "styles.css"]) {
				fs.copyFileSync(f, path.join(outDir, f));
			}
			if (fs.existsSync("fonts")) {
				const fontsDst = path.join(outDir, "fonts");
				fs.mkdirSync(fontsDst, { recursive: true });
				for (const f of fs.readdirSync("fonts")) {
					if (f.endsWith(".woff2")) {
						fs.copyFileSync(path.join("fonts", f), path.join(fontsDst, f));
					}
				}
			}
			console.log(`[sync] manifest.json, styles.css, fonts/*.woff2 → ${outDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	plugins: [syncStatics],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
